### ISSUE TITLE
Ошибки а режиме $arParams['CACHE_TYPE'] = 'N '

### ISSUE THREAD

**Issue by StanislavDremin** [DigitalWand/mvc.base#1]
При настройке компонента $arParams['CACHE_TYPE'] = 'N ' DigitalWand\MVC\BaseComponent::getActionCacheID все равно возвращает ID кешa вместо false и кеширование срабатывает.

В этом же методе из-за  return $this->componentRoute . var_export($this->componentRouteVariables) . (is_null($cacheID) ? '' : $cacheID);

В шаблоне всегда перед контентом висит строка array()

Вылечил все это дело таким способом 
 ```
private function getActionCacheID($cacheID = null)
    {
    	if($this->arParams['CACHE_TYPE'] == 'N')
    		return false;

        return $this->componentRoute . md5(serialize($this->componentRouteVariables)) . (is_null($cacheID) ? '' : $cacheID);
    }
```

Далее, в методе DigitalWand\MVC\BaseComponent::callActionFunction если выключен кеш, то ничего не возвращается и шаблон не рендерится.
Вылечил так:
```
 if ($cacheOptions === false) {
   .....

         if ($response === false) {
                throw new \Exception("Error executing route's {$this->componentRoute} action");
            } elseif (!$this->isTemplateRendered() && !$this->isRestMode()) {
	            $componentPage = $this->componentRoute ? $this->componentRoute : '';
	            $this->includeComponentTemplate($componentPage);
            }
}
```

**Comment by ASGAlex** [comment]
Я несколько против md5 и serialize - это только поедает ресурсы, которые и так нещадно жрёт битрикс, да и сам роутинг этого модуля. 

Спасибо за багрепорт, в основном это моя невнимательность :-)
